### Analyzer and Linter Configuration
include: package:flutter_lints/flutter.yaml

analyzer:
  # Exclude generated files and build artifacts from analysis
  exclude:
    - 'build/**'
    - '.dart_tool/**'
    - 'lib/**.g.dart'
    - 'lib/**.freezed.dart'

linter:
  rules:
    # Allow print debugging in development
    avoid_print: false
    # Enforce consistent use of single quotes
    prefer_single_quotes: true
    # Always use braces in flow control for clarity
    curly_braces_in_flow_control_structures: true
    # Prefer const constructors for widgets
    prefer_const_constructors: true
    # Prefer final for local variables when possible
    prefer_final_locals: true
    # Use package imports instead of relative paths
    always_use_package_imports: true
    # Keep pubspec dependencies sorted
    sort_pub_dependencies: true
    # Avoid redundant argument values
    avoid_redundant_argument_values: true
    # Prefer const literals for immutability
    prefer_const_literals_to_create_immutables: true
